version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.9'
sphinx:
  configuration: doc/conf.py
python:
  install:
    - path: .
      method: pip
      extra_requirements:
        - avro
    - requirements: doc/requirements.txt
